01 — Business Problem

The objective is to clean and validate Amazon e-commerce sales transaction data and prepare it for reliable business analysis.

02 — Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

03 — Load Dataset

In [2]:
df = pd.read_csv("C:/Users/Mangesh/Desktop/manju/sETUP/Amazon Sale Report.csv")

C:\Users\Mangesh\AppData\Local\Temp\ipykernel_4568\1727978454.py:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:/Users/Mangesh/Desktop/manju/sETUP/Amazon Sale Report.csv")

04 — Initial Data Inspection

In [3]:
df.shape

(128975, 24)

In [4]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [5]:
df.tail()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
128970,128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,...,INR,517.0,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN,False
128971,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,...,INR,999.0,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128972,128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,...,INR,690.0,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN,False
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,INR,1199.0,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128974,128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,...,INR,696.0,Raipur,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

In [7]:
df.describe(include="all")

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
count,128975.000000,128975,128975,128975,128975,128975,128975,128975,128975,128975,...,121180,121180.000000,128942,128942,128942.000000,128942,79822,128975,39277,79925
unique,NaN,120378,91,13,2,2,2,1377,7195,9,...,1,NaN,8955,69,NaN,1,5787,2,1,1
top,NaN,171-5057375-2831560,05-03-22,Shipped,Amazon,Amazon.in,Expedited,JNE3797,JNE3797-KR-L,Set,...,INR,NaN,BENGALURU,MAHARASHTRA,NaN,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Easy Ship,False
freq,NaN,12,2085,77804,89698,128851,88615,4224,773,50284,...,121180,NaN,11217,22260,NaN,128942,46100,128104,39277,79925
mean,64487.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,648.561465,NaN,NaN,463966.236509,NaN,NaN,NaN,NaN,NaN
std,37232.019822,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,281.211687,NaN,NaN,191476.764941,NaN,NaN,NaN,NaN,NaN
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000,NaN,NaN,110001.000000,NaN,NaN,NaN,NaN,NaN
25%,32243.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,449.000000,NaN,NaN,382421.000000,NaN,NaN,NaN,NaN,NaN
50%,64487.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,605.000000,NaN,NaN,500033.000000,NaN,NaN,NaN,NaN,NaN
75%,96730.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,788.000000,NaN,NaN,600024.000000,NaN,NaN,NaN,NaN,NaN
max,128974.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,5584.000000,NaN,NaN,989898.000000,NaN,NaN,NaN,NaN,NaN

05 — Data Quality Assessment

In [8]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

In [9]:
df.duplicated().sum()

0

Step 6 — Data Cleaning

6.1 Clean column names

In [10]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

6.2 Clean text/categorical columns

In [11]:
text_columns = [
    'status',
    'fulfilment',
    'sales_channel',
    'ship_service_level',
    'style',
    'sku',
    'category',
    'size',
    'asin',
    'courier_status',
    'ship_city',
    'ship_state',
    'ship_country',
    'b2b',
    'fulfilled_by'
]

In [12]:
for col in text_columns:
    df[col] = df[col].astype("string").str.strip()

6.3 Clean the date

In [13]:
df['date'] = pd.to_datetime(
    df['date'],
    format='%m-%d-%y',
    errors='coerce'
)

In [14]:
df['date'].isna().sum()

0

In [15]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['month_name'] = df['date'].dt.month_name()

In [16]:
df[['date', 'year', 'month', 'month_name']].head(10)

        date  year  month month_name
0 2022-04-30  2022      4      April
1 2022-04-30  2022      4      April
2 2022-04-30  2022      4      April
3 2022-04-30  2022      4      April
4 2022-04-30  2022      4      April
5 2022-04-30  2022      4      April
6 2022-04-30  2022      4      April
7 2022-04-30  2022      4      April
8 2022-04-30  2022      4      April
9 2022-04-30  2022      4      April

6.4 Clean numerical columns

In [17]:
numeric_columns = ['qty', 'amount']

In [18]:
for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [19]:
df[numeric_columns].describe()

                 qty         amount
count  128975.000000  121180.000000
mean        0.904431     648.561465
std         0.313354     281.211687
min         0.000000       0.000000
25%         1.000000     449.000000
50%         1.000000     605.000000
75%         1.000000     788.000000
max        15.000000    5584.000000

In [20]:
df[df['qty'] < 0]
df[df['amount'] < 0]

Empty DataFrame
Columns: [index, order_id, date, status, fulfilment, sales_channel, ship_service_level, style, sku, category, size, asin, courier_status, qty, currency, amount, ship_city, ship_state, ship_postal_code, ship_country, promotion_ids, b2b, fulfilled_by, unnamed:_22, year, month, month_name]
Index: []

[0 rows x 27 columns]

6.5 Investigate missing values

In [21]:
df[df['amount'].isna()][
    ['status', 'qty', 'currency', 'amount']
].value_counts()

Series([], Name: count, dtype: int64)

In [22]:
df[df['currency'].isna()][
    ['status', 'qty', 'amount']
].head()

       status  qty  amount
8   Cancelled    0     NaN
29  Cancelled    0     NaN
65  Cancelled    0     NaN
84  Cancelled    0     NaN
95  Cancelled    0     NaN

6.6 Standardize locations

In [23]:
df['ship_city'].value_counts().head(30)

ship_city
BENGALURU             11217
HYDERABAD              8074
MUMBAI                 6126
NEW DELHI              5795
CHENNAI                5421
PUNE                   3857
KOLKATA                2381
GURUGRAM               1868
THANE                  1701
LUCKNOW                1458
NOIDA                  1419
GHAZIABAD              1328
NAVI MUMBAI            1263
AHMEDABAD              1236
JAIPUR                  948
Hyderabad               919
Mumbai                  868
COIMBATORE              768
PATNA                   764
VISAKHAPATNAM           761
Bangalore               734
Chennai                 731
PIMPRI CHINCHWAD        723
FARIDABAD               700
BHUBANESWAR             694
GUWAHATI                676
Bengaluru               669
Pune                    661
THIRUVANANTHAPURAM      630
NAGPUR                  629
Name: count, dtype: Int64

In [24]:
df['ship_city'] = (
    df['ship_city']
    .astype("string")
    .str.strip()
    .str.upper()
    .str.rstrip(".")
)

In [25]:
df['ship_city'].value_counts().head(30)

ship_city
BENGALURU             11900
HYDERABAD              9128
MUMBAI                 7124
NEW DELHI              6340
CHENNAI                6288
PUNE                   4618
KOLKATA                2844
GURUGRAM               1956
THANE                  1877
LUCKNOW                1627
NOIDA                  1627
GHAZIABAD              1485
AHMEDABAD              1445
NAVI MUMBAI            1403
BANGALORE              1362
JAIPUR                 1062
COIMBATORE              891
VISAKHAPATNAM           858
FARIDABAD               820
PATNA                   816
BHUBANESWAR             780
PIMPRI CHINCHWAD        754
GUWAHATI                740
NAGPUR                  733
VADODARA                710
THIRUVANANTHAPURAM      679
DEHRADUN                633
SECUNDERABAD            623
GREATER NOIDA           564
SURAT                   564
Name: count, dtype: Int64

In [26]:
df[df['ship_city'].isin(['BANGALORE', 'BENGALURU'])]['ship_city'].value_counts()

ship_city
BENGALURU    11900
BANGALORE     1362
Name: count, dtype: Int64

In [27]:
df['ship_city'] = df['ship_city'].replace({
    'BANGALORE': 'BENGALURU'
})

In [28]:
df['ship_city'].value_counts().head(30)

ship_city
BENGALURU             13262
HYDERABAD              9128
MUMBAI                 7124
NEW DELHI              6340
CHENNAI                6288
PUNE                   4618
KOLKATA                2844
GURUGRAM               1956
THANE                  1877
LUCKNOW                1627
NOIDA                  1627
GHAZIABAD              1485
AHMEDABAD              1445
NAVI MUMBAI            1403
JAIPUR                 1062
COIMBATORE              891
VISAKHAPATNAM           858
FARIDABAD               820
PATNA                   816
BHUBANESWAR             780
PIMPRI CHINCHWAD        754
GUWAHATI                740
NAGPUR                  733
VADODARA                710
THIRUVANANTHAPURAM      679
DEHRADUN                633
SECUNDERABAD            623
SURAT                   564
GREATER NOIDA           564
INDORE                  557
Name: count, dtype: Int64

07. Data Validation

7.1 Check duplicate rows

In [29]:
df.duplicated().sum()

0

7.2 Check duplicate Order IDs

In [30]:
df['order_id'].duplicated().sum()

8597

7.3 Check missing values

In [31]:
missing = df.isnull().sum()

missing[missing > 0].sort_values(ascending=False)

fulfilled_by        89698
promotion_ids       49153
unnamed:_22         49050
currency             7795
amount               7795
courier_status       6872
ship_city              33
ship_state             33
ship_postal_code       33
ship_country           33
dtype: int64

7.4 Check data types

In [32]:
df.dtypes

index                          int64
order_id                      object
date                  datetime64[ns]
status                string[python]
fulfilment            string[python]
sales_channel         string[python]
ship_service_level    string[python]
style                 string[python]
sku                   string[python]
category              string[python]
size                  string[python]
asin                  string[python]
courier_status        string[python]
qty                            int64
currency                      object
amount                       float64
ship_city             string[python]
ship_state            string[python]
ship_postal_code             float64
ship_country          string[python]
promotion_ids                 object
b2b                   string[python]
fulfilled_by          string[python]
unnamed:_22                   object
year                           int32
month                          int32
month_name                    object
dtype: object

In [33]:
print("Date:", df['date'].dtype)
print("Quantity:", df['qty'].dtype)
print("Amount:", df['amount'].dtype)

Date: datetime64[ns]
Quantity: int64
Amount: float64

In [34]:
df[['qty', 'amount']].describe()

                 qty         amount
count  128975.000000  121180.000000
mean        0.904431     648.561465
std         0.313354     281.211687
min         0.000000       0.000000
25%         1.000000     449.000000
50%         1.000000     605.000000
75%         1.000000     788.000000
max        15.000000    5584.000000

7.5 Check negative values

In [35]:
print("Negative Qty:", (df['qty'] < 0).sum())
print("Negative Amount:", (df['amount'] < 0).sum())

Negative Qty: 0
Negative Amount: 0

7.6 Check date range

In [36]:
print("Minimum date:", df['date'].min())
print("Maximum date:", df['date'].max())

Minimum date: 2022-03-31 00:00:00
Maximum date: 2022-06-29 00:00:00

7.7 Check important categorical columns

In [37]:
print("Status:")
print(df['status'].value_counts(dropna=False))

Status:
status
Shipped                          77804
Shipped - Delivered to Buyer     28769
Cancelled                        18332
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: Int64

In [38]:
print("\nCategory:")
print(df['category'].value_counts(dropna=False))

Category:
category
Set              50284
kurta            49877
Western Dress    15500
Top              10622
Ethnic Dress      1159
Blouse             926
Bottom             440
Saree              164
Dupatta              3
Name: count, dtype: Int64

In [39]:
print("\nFulfilment:")
print(df['fulfilment'].value_counts(dropna=False))

Fulfilment:
fulfilment
Amazon      89698
Merchant    39277
Name: count, dtype: Int64

In [40]:
print("\nB2B:")
print(df['b2b'].value_counts(dropna=False))

B2B:
b2b
False    128104
True        871
Name: count, dtype: Int64

08. Before vs After Quality Report

In [41]:
after_metrics = {
    'Total Rows': len(df),
    'Total Columns': len(df.columns),
    'Duplicate Rows': df.duplicated().sum(),
    'Missing Values': df.isnull().sum().sum(),
    'Negative Quantity': (df['qty'] < 0).sum(),
    'Negative Amount': (df['amount'] < 0).sum()
}

after_metrics

{'Total Rows': 128975,
 'Total Columns': 27,
 'Duplicate Rows': 0,
 'Missing Values': 210495,
 'Negative Quantity': 0,
 'Negative Amount': 0}

Report

In [42]:
quality_report = pd.DataFrame({
    'Metric': [
        'Total Rows',
        'Total Columns',
        'Duplicate Rows',
        'Missing Values',
        'Negative Quantity',
        'Negative Amount'
    ],
    
    'Before': [
        # Put your Step 5 values here
        0,
        0,
        0,
        0,
        0,
        0
    ],
    
    'After': [
        after_metrics['Total Rows'],
        after_metrics['Total Columns'],
        after_metrics['Duplicate Rows'],
        after_metrics['Missing Values'],
        after_metrics['Negative Quantity'],
        after_metrics['Negative Amount']
    ]
})

quality_report

              Metric  Before   After
0         Total Rows       0  128975
1      Total Columns       0      27
2     Duplicate Rows       0       0
3     Missing Values       0  210495
4  Negative Quantity       0       0
5    Negative Amount       0       0

In [43]:
print("Rows:", len(df))
print("Columns:", len(df.columns))
print("Negative Quantity:", (df['qty'] < 0).sum())
print("Negative Amount:", (df['amount'] < 0).sum())

Rows: 128975
Columns: 27
Negative Quantity: 0
Negative Amount: 0